multiplication:
  # task
  seed: 1
  # data
  p: 97
  split_ratio: 0.5
  batch_size: 512
  # optimizer
  budget: 100000
  lr: 1e-4
  beta1: 0.9
  beta2: 0.98
  weight_decay: 1
  optimizer: "AdamW"
  # grokfast
  filter: "none"
  alpha: 0.99
  window_size: 100
  lamb: 5.0
  # hessian
  no_hessian: False
  hessian_save_every: 100
  explicit_hessian_regularization: 0
  # nsm
  nsm_sigma: 0.01
  nsm_distribution: "normal"
  sam_rho: 0.05
sum_of_squares:
  # task
  seed: 1
  # data
  p: 97
  split_ratio: 0.5
  batch_size: 512
  # optimizer
  budget: 100000
  lr: 1e-4
  beta1: 0.9
  beta2: 0.98
  weight_decay: 1
  optimizer: "AdamW"
  # grokfast
  filter: "none"
  alpha: 0.99
  window_size: 100
  lamb: 5.0
  # hessian
  no_hessian: False
  hessian_save_every: 100
  explicit_hessian_regularization: 0
  # nsm
  nsm_sigma: 0.01
  nsm_distribution: "normal"
  sam_rho: 0.05
quad1:
  # task
  seed: 5
  # data
  p: 97
  split_ratio: 0.9
  batch_size: 512
  # optimizer
  budget: 140000
  lr: 1e-4
  beta1: 0.9
  beta2: 0.98
  weight_decay: 1
  optimizer: "AdamW"
  # grokfast
  filter: "none"
  alpha: 0.99
  window_size: 100
  lamb: 5.0
  # hessian
  no_hessian: False
  hessian_save_every: 100
  explicit_hessian_regularization: 0
  # nsm
  nsm_sigma: 0.01
  nsm_distribution: "normal"
  sam_rho: 0.05
quad2:
  # task
  seed: 1
  # data
  p: 97
  split_ratio: 0.9
  batch_size: 512
  # optimizer
  budget: 300000
  lr: 1e-4
  beta1: 0.9
  beta2: 0.98
  weight_decay: 1
  optimizer: "AdamW"
  # grokfast
  filter: "none"
  alpha: 0.99
  window_size: 100
  lamb: 5.0
  # hessian
  no_hessian: False
  hessian_save_every: 300
  explicit_hessian_regularization: 0
  # nsm
  nsm_sigma: 0.01
  nsm_distribution: "normal"
  sam_rho: 0.05
cubic1:
  # task
  seed: 1
  # data
  p: 97
  split_ratio: 0.9
  batch_size: 512
  # optimizer
  budget: 800000
  lr: 1e-4
  beta1: 0.9
  beta2: 0.98
  weight_decay: 1
  optimizer: "AdamW"
  # grokfast
  filter: "none"
  alpha: 0.99
  window_size: 100
  lamb: 5.0
  # hessian
  no_hessian: False
  hessian_save_every: 100
  explicit_hessian_regularization: 0
  # nsm
  nsm_sigma: 0.01
  nsm_distribution: "normal"
  sam_rho: 0.05
